[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Patrick", email = "10087322+pmillar360@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = [
    "alembic",
    "bcrypt",
    "fastapi",
    "psycopg2-binary",
    "pydantic",
    "python-dotenv",
    "python-jose",
    "python-multipart",
    "requests",
    "sqlalchemy",
    "uvicorn",
]

[dependency-groups]
dev = [
    "pytest",
    "pytest-asyncio",
    "pytest-cov",
    "httpx2",
]


[tool.uv]
package = false

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"
