"""add missing columns to recipes and ingredients

Revision ID: 98aaf7a00788
Revises: 
Create Date: 2025-03-31 18:15:23.140708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98aaf7a00788'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredients', sa.Column('category', sa.String(), nullable=True))
    op.create_index(op.f('ix_ingredients_category'), 'ingredients', ['category'], unique=False)
    op.add_column('recipe_ingredient', sa.Column('quantity', sa.String(), nullable=True))
    op.add_column('recipe_ingredient', sa.Column('unit', sa.String(), nullable=True))
    op.add_column('recipes', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('recipes', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'recipes', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipes', type_='foreignkey')
    op.drop_column('recipes', 'user_id')
    op.drop_column('recipes', 'description')
    op.drop_column('recipe_ingredient', 'unit')
    op.drop_column('recipe_ingredient', 'quantity')
    op.drop_index(op.f('ix_ingredients_category'), table_name='ingredients')
    op.drop_column('ingredients', 'category')
    # ### end Alembic commands ###
